language: php

php:
    - 5.5
    - 5.4

before_script:
    - /home/travis/.phpenv/versions/`phpenv version-name`/bin/composer self-update
    - composer --version
    - composer update

script: phpunit --configuration tests/phpunit.xml
