language: php

php:
    - 5.5
    - 5.4
    - 5.3

before_script:
    - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    - composer update

script: phpunit --configuration tests/phpunit.xml
