language: php
php:
  - 5.6
  - 7.1
  - 7.2
  - master

env:
  - dependencies=lowest
  - dependencies=highest

matrix:
  allow_failures:
    - php: master
      env: dependencies=lowest
    - php: master
      env: dependencies=highest

before_script:
  - composer self-update
  - if [ "$dependencies" = "lowest" ];  then composer update --no-interaction --prefer-lowest; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction; fi;

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit
    - if [ "$TRAVIS_PHP_VERSION" != "5.6" && "$dependencies" = "highest" ]; then composer require --dev phpstan/phpstan; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "5.6" && "$dependencies" = "highest" ]; then php vendor/bin/phpstan analyze src tests; fi;

after_script:
    - php vendor/bin/php-coveralls -v
    - CODECLIMATE_REPO_TOKEN="1236a1650f2cb22f334ec37e96e7e022d11cbf1a8e604a99fc59a3501810fdc6" vendor/bin/test-reporter --stdout > codeclimate.json
    - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
